[package]
name = "bfl"
version = "0.1.0"
authors = ["re:Zer0dAI <tutti@frutti.com>"]

[lib]
name = "libbfl"
path = "src/lib.rs"
doc = false

[dependencies]
core = { path = "../../core" }
generic = { path = "../../generic" }
serde = "1.0.131"
serde_derive = "1.0.131"
libc = "0.2.109"
